### PR TITLE
Overflowing filter summary now wraps to next line

### PR DESCRIPTION
**Pull request by Blackbaud-AlexKingman**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-lists?_sp.spa=pr-filter-summary-overflow](https://developer.blackbaud.com/skyux-lists?_sp.spa=pr-filter-summary-overflow)

**Review by Blackbaud-ToddRoberts — CHANGES_REQUESTED** [review]
needs vertical spacing when wrapped in modern theme

image

**Comment by Blackbaud-AlexKingman** [comment]
> needs vertical spacing when wrapped in modern theme
> 
> image

Added spacing.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-lists?_sp.spa=pr-filter-summary-overflow](https://developer.blackbaud.com/skyux-lists?_sp.spa=pr-filter-summary-overflow)

**Review by Blackbaud-ToddRoberts — APPROVED** [review]

**Review by johnhwhite — APPROVED** [review]

**Pull request merged**
